### ISSUE TITLE
Cannot clone repo

### ISSUE THREAD

**Issue by MudDev** [eco-stake/validator-registry#1411]
Perhaps this is an issue with windows, but we cannot clone due to emoji's being used in the path

![image](https://user-images.githubusercontent.com/44410798/199355821-488f5816-0ec2-43db-b330-030479cf46a5.png)

**Comment by tombeynon** [comment]
Interesting - that's good to know! It must just be a Windows issue but definitely needs resolving. I've been considering normalising all the directories and applying some validation for new submissions, so I'll look to sort that ASAP.

**Comment by Bosco-2019** [comment]
Hey @tombeynon 

Just wondering if there is any update on this? I've searched high and low for a resolution to this issue but the only answer I keep coming across is to rename the problem directory.

**Comment by AutoStake-net** [comment]
What command did you use to git clone?

**Comment by tombeynon** [comment]
Sorry @Bosco-2019 I missed this! I just need to do a PR removing all the emojis really. Ideally I would setup a validation for it but I just don't have time right now, so we can manually keep an eye for now. 

I'll sort that this week, promise. Let me know if you need me to submit anything on your behalf in the meantime, appreciate this is a pain.

**Comment by Bosco-2019** [comment]
@AutoStake-net using GitHub Desktop and VS code, pretty sure there's just some sort of incompatibility with one vals emojis that stopping me from pulling. 

Thanks, @tombeynon no worries at all pal, appreciate all you do.

**Comment by MudDev** [comment]
@AutoStake-net `git clone https://github.com/eco-stake/validator-registry.git`

**Result:**
```
Cloning into 'validator-registry'...
remote: Enumerating objects: 11973, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (276/276), done.
remote: Total 11973 (delta 170), reused 354 (delta 127), pack-reused 11559
Receiving objects: 100% (11973/11973), 3.21 MiB | 4.98 MiB/s, done.
Resolving deltas: 100% (4922/4922), done.
error: invalid path 'JambulMerah | Cosmos⚛️Lover❤️/chains.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by AutoStake-net** [comment]
@MudDev try using GitBash https://gitforwindows.org/

It was life saver for me when an employer forced me to use Windows after a lifetime of me using Linux

**Comment by MudDev** [comment]
@AutoStake-net - Yes, this output was from gitbash.

**Comment by azharimad** [comment]
any update for this? i face same problem using github windows

**Comment by tombeynon** [comment]
This should now be fixed, and new directories will be validated automatically moving forward.
