### ISSUE TITLE
Read validator logo from cosmosation registery

### ISSUE THREAD

**Issue by alighasemzadeh** [eco-stake/validator-registry#16]
Now we read validator icon from keybase.io but we can read from cosmostation registry.
Or they put in this repo.

**Comment by tombeynon** [comment]
Validator registry doesn't do anything with images currently. REStake uses keybase.io if that's what you mean.

I think this could be a good source of validator images in the future, and ultimately validators can put whatever they want into this repo (within reason). But for now I don't want to duplicate effort. The cosmos.directory API will return properties like mintscan image soon, the intention there is to bring together all the cosmos data scattered in different repositories.

**Comment by alighasemzadeh** [comment]
I agree with you.
While validator register in cosmosation doesn't need to reregister here only wallet,times of restake needed.

**Comment by tombeynon** [comment]
cosmos.directory API will now return both mintscan and keybase image URLs: https://github.com/eco-stake/cosmos-directory#get-chainschain

And REStake now uses mintscan image first, and falls back to Keybase image: https://github.com/eco-stake/restake/pull/418
