### ISSUE TITLE
multiple bots

### ISSUE THREAD

**Issue by marbar3778** [eco-stake/validator-registry#20]
I have multiple bots running but with this repo the newer bots are reading from here and auto compounding at times it shouldn't, is there a way to avoid this?

**Comment by tombeynon** [comment]
Sorry not sure I follow - the time you run restake is purely down to your script. The information in this repo/previously in restake was just to show delegators what time you plan to run it.

**Comment by marbar3778** [comment]
I ran the bot manually and it restocked for osmosis and Umee but was only meant to run for the cosmos hub. How do I make it only run for the hub?

**Comment by marbar3778** [comment]
do I remove all networks in network.json?

**Comment by tombeynon** [comment]
You can run a single network with `... run autostake cosmoshub`. The setup for running multiple networks at different times would look something like this:

```
0 21 * * * /bin/bash -c "cd restake && docker-compose run --rm app npm run autostake osmosis" > ./restake.osmosis.log 2>&1
0 * * * * /bin/bash -c "cd restake && docker-compose run --rm app npm run autostake cerberus" > ./restake.cerberus.log 2>&1
0 9,21 * * * /bin/bash -c "cd restake && docker-compose run --rm app npm run autostake cosmoshub" > ./restake.cosmoshub.log 2>&1
```

It's important to understand the the autostake script runs the autostake _at that time_, it doesn't take into account _when_ you said you'll run it. It's up to you to run it at the right time for each network.

**Comment by tombeynon** [comment]
You shouldn't need to change networks.json at all now. networks.local.json is useful for setting your own node, or adjusting some of the autostaking parameters for each network such as batch size. More in the restake README on that.

**Comment by marbar3778** [comment]
ah I forgot about the single part, thank you

**Comment by tombeynon** [comment]
Funny you should mention, that was added last night!

**Comment by activenodes** [comment]
> Funny you should mention, that was added last night!

Oh, wow! well done :)
