### ISSUE TITLE
Failed to get delegations: Request failed with status code 524

### ISSUE THREAD

**Issue by freemanhk** [eco-stake/validator-registry#303]
Hello,

We are trying to setup the restake service for Likecoin by adding manually the entry into network.json and the execution looks fine but face an issue as not able to get delegations list.
Log is as below:
[04:10:30.583] Running autostake
[04:10:31.346] Bot balance is 10000000000 nanolike
[04:10:31.347] Finding delegators...
[04:12:10.672] Failed to get delegations: Request failed with status code 524
[04:12:10.672] Checking 0 delegators for grants...

Any suggestion?

**Comment by tombeynon** [comment]
Interesting.. is it using cosmos.directory for the REST URL? 524 is a Cloudflare specific gateway timeout, and I wouldn't expect it to happen every time. It could be an issue with the public node as there is only one - you could try overriding `restUrl` in the config to one of your own nodes, with the `api.enable` tendermint config set to `true`.

**Comment by freemanhk** [comment]
yes. I was using cosmos.directory for the REST URL. 
Will test with my own node.

**Comment by freemanhk** [comment]
> Interesting.. is it using cosmos.directory for the REST URL? 524 is a Cloudflare specific gateway timeout, and I wouldn't expect it to happen every time. It could be an issue with the public node as there is only one - you could try overriding `restUrl` in the config to one of your own nodes, with the `api.enable` tendermint config set to `true`.

I can arrange to do the restake for Likecoin Chain using my own RPC and API server.
