### ISSUE TITLE
Added chain "sentinel" not working as expected.

### ISSUE THREAD

**Issue by ourlink** [eco-stake/validator-registry#3046]
We recently submitted a PR for the addition of Sentinel network to our Restaking network resources.
[https://github.com/eco-stake/validator-registry/blob/master/ValidatorNode/chains.json](https://github.com/eco-stake/validator-registry/blob/master/ValidatorNode/chains.json)

We updated our ``networks.local.json`` file to include the new sentinel network
```
  "sentinel": {
    "enabled": true,
    "prettyName": "Sentinel",
    "restUrl": [
      "http://216.128.136.66:1317"
    ],
    "gasPrice": "0.01udvpn",
    "autostake": {
      "correctSlip44": true,
      "retries": 3,
      "batchPageSize": 100,
      "batchQueries": 25,
      "batchTxs": 50,
      "delegationsTimeout": 20000,
      "queryTimeout": 15000,
      "queryThrottle": 100,
      "gasModifier": 1.1
    }
```
We ensured that the firewall on our restURL server is allowing traffic to port 1317.

However, when we attempt to ``npm run dryrun sentinel`` we receive the following error.
```
> restake@0.1.0 dryrun
> node scripts/dryrun.mjs "sentinel"

[16:17:45.386] ⚛
[16:17:47.073] Loaded Sentinel
[16:17:47.137] Bot address is sent1xgcqw2flkaxffe0s5kctlnelyshe87vh9aaxgs
[16:17:47.137] Not an operator
[16:17:47.137] Autostake finished
```

The error leads us to believe that the Restake **dryrun** script is not picking up our recent validator-registry changes.
We've double-checked the normal list of issues

1. indexing enabled 
2. minimum gas prices matching our restURL server setting

What else can we check?

NOTE - the other 3 networks we have configured are all running fine. It's just the newly added **"sentinel"** network that is creating us an issue.

**Comment by ourlink** [comment]
How does the BOT determine which BOT address it is going to use?
I thought that the BOT would pull the address we input into the validator registry.

**Comment by tombeynon** [comment]
It doesn't have a choice like that - it uses the mnemonic and the slip44 you define to derive the address. Here you're using `correctSlip44` which essentially uses the slip44 defined in the Chain Registry.

**Comment by ourlink** [comment]
Understand now.
It is working so I'll close this for now.
