### ISSUE TITLE
Still not a REStake operator ?

### ISSUE THREAD

**Issue by eric821031** [eco-stake/validator-registry#4574]
Hi eco-stake team,

I'm a Cosmos Hub validator operating as biglazycat.com. Recently, I added my information to the validator-registry master directory, and my pull request has been successfully merged. However, my validator is still not listed as an REStake operator on [restake.app](https://restake.app/) – it continues to display as "not a REStake operator."

Could you please check if I may have missed any steps, or if there’s a standard delay before the status updates?

Thanks very much for your assistance!

Best regards,
Eric

**Comment by tombeynon** [comment]
Hi @eric821031, just checked your chains.json and your address here should be your validator address. 

https://github.com/eco-stake/validator-registry/blob/master/biglazycat.com/chains.json#L7

Submit a PR and I'll get it merged. Should only be a 15 min delay max after merging.

**Comment by eric821031** [comment]
Thanks @tombeynon !
